export const CELDA = 24;
export const COLUMNAS = 80;
export const FILAS = 55;
export const ANCHO = COLUMNAS * CELDA;
export const ALTO = FILAS * CELDA;

export const T = {
    salonH24izq:   1,
    salonH23:      2,
    salonH22:      3,
    pasilloBloqueH: 4,
    gradasBloqueH:  5,
    miniSalonH25:   6,
    miniSalonH26:   7,
    pasilloConectorH: 8,
    coordinacion:  9,
    salonG25:     10,
    salonG24:     11,
    serviciosSS:  12,
    salonG21:     13,
    pasilloCentral: 14,
    gradasG:       15,
    gradasConector: 16,
    oficina1:      17,
    oficina2:      18,
    laboratorioTics: 19,
    pasilloEste:   20,
    preceptorias:  21,
    salaReuniones: 22,
    gradasBloqueB: 23,
    salonB22der:   24,
    salonB21der:   25,
    areaVerde:     26,
    pasilloHorizontalDer: 27,
};

export const COLORES = {
    [T.salonH24izq]:        '#b0b0b0',
    [T.salonH23]:           '#b0b0b0',
    [T.salonH22]:           '#b0b0b0',
    [T.pasilloBloqueH]:     '#f5c842',
    [T.gradasBloqueH]:      '#4ecdc4',
    [T.miniSalonH25]:       '#b0b0b0',
    [T.miniSalonH26]:       '#b0b0b0',
    [T.pasilloConectorH]:   '#f5c842',
    [T.coordinacion]:       '#b0b0b0',
    [T.salonG25]:           '#b0b0b0',
    [T.salonG24]:           '#b0b0b0',
    [T.serviciosSS]:        '#b0b0b0',
    [T.salonG21]:           '#b0b0b0',
    [T.pasilloCentral]:     '#f5c842',
    [T.gradasG]:            '#4ecdc4',
    [T.gradasConector]:     '#4ecdc4',
    [T.oficina1]:           '#b0b0b0',
    [T.oficina2]:           '#b0b0b0',
    [T.laboratorioTics]:    '#b0b0b0',
    [T.pasilloEste]:        '#f5c842',
    [T.preceptorias]:       '#b0b0b0',
    [T.salaReuniones]:      '#b0b0b0',
    [T.gradasBloqueB]:      '#4ecdc4',
    [T.salonB22der]:        '#b0b0b0',
    [T.salonB21der]:        '#b0b0b0',
    [T.areaVerde]:          '#5dbb63',
    [T.pasilloHorizontalDer]: '#f5c842',
};

export const BORDE = {
    [T.salonH24izq]:        '#555',
    [T.salonH23]:           '#555',
    [T.salonH22]:           '#555',
    [T.pasilloBloqueH]:     '#c9970a',
    [T.gradasBloqueH]:      '#289991',
    [T.miniSalonH25]:       '#555',
    [T.miniSalonH26]:       '#555',
    [T.pasilloConectorH]:   '#c9970a',
    [T.coordinacion]:       '#555',
    [T.salonG25]:           '#555',
    [T.salonG24]:           '#555',
    [T.serviciosSS]:        '#555',
    [T.salonG21]:           '#555',
    [T.pasilloCentral]:     '#c9970a',
    [T.gradasG]:            '#289991',
    [T.gradasConector]:     '#289991',
    [T.oficina1]:           '#555',
    [T.oficina2]:           '#555',
    [T.laboratorioTics]:    '#555',
    [T.pasilloEste]:        '#c9970a',
    [T.preceptorias]:       '#555',
    [T.salaReuniones]:      '#555',
    [T.gradasBloqueB]:      '#289991',
    [T.salonB22der]:        '#555',
    [T.salonB21der]:        '#555',
    [T.areaVerde]:          '#2e7d32',
    [T.pasilloHorizontalDer]: '#c9970a',
};

export const lugaresEnMapa = [
    { nombre: 'Clase H24',        fila: 14, columna: 5  },
    { nombre: 'Clase H23',        fila: 22, columna: 5  },
    { nombre: 'Clase H22',        fila: 30, columna: 5  },
    { nombre: 'Clase G25',        fila: 8,  columna: 27 },
    { nombre: 'Clase G24',        fila: 14, columna: 27 },
    { nombre: 'SS',               fila: 20, columna: 24 },
    { nombre: 'Clase G21',        fila: 26, columna: 24 },
    { nombre: 'Coordinacion',     fila: 4,  columna: 27 },
    { nombre: 'Oficina 1',        fila: 35, columna: 42 },
    { nombre: 'Oficina 2',        fila: 40, columna: 42 },
    { nombre: 'Tics',             fila: 46, columna: 47 },
    { nombre: 'Sala de Reuniones',fila: 18, columna: 62 },
    { nombre: 'Clase B22',        fila: 22, columna: 73 },
    { nombre: 'Clase B21',        fila: 30, columna: 73 },
    { nombre: 'Gradas H',         fila: 8,  columna: 18 },
    { nombre: 'Gradas G',         fila: 28, columna: 36 },
    { nombre: 'Gradas B',         fila: 26, columna: 68 },
];